{"name": "test_integer_add[整数加法_结果4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 101 == 100", "trace": "self = <python_scripts.third_pytest_scripts_01.TestCase_Calculator.TestCal.TestCalculator object at 0x7fa49aac6dd0>, a = 89, b = 11\nexpect = 101\n\n    @allure.story(\"整数加法\")\n    @pytest.mark.parametrize(\n        ['a', 'b', 'expect'],\n        [data for data in get_data('integer_add')],\n        ids=[\n            '整数加法_结果1',\n            '整数加法_结果2',\n            '整数加法_结果3',\n            '整数加法_结果4'\n        ])\n    def test_integer_add(self, a, b, expect):\n        result = self.cal.add(a, b)\n>       assert expect == result\nE       assert 101 == 100\n\nTestCal.py:63: AssertionError"}, "parameters": [{"name": "a", "value": "89"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "101"}], "start": 1597461583089, "stop": 1597461583089, "uuid": "88f2b601-f7db-47ad-8ab0-ba4439584db8", "historyId": "b9f2066a336b780623798e5c35a19331", "testCaseId": "6827ed8a49cd5bcd3667adc9377a02af", "fullName": "TestCal.TestCalculator#test_integer_add", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "整数加法"}, {"name": "suite", "value": "TestCal"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "CreamK"}, {"name": "thread", "value": "65678-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCal"}]}